name: flutter_auth_app
description: Flutter authentication app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  google_generative_ai: ^0.4.7
  just_audio: ^0.10.3
  audioplayers: ^6.4.0

assets:
  - assets/audio/
  -  .env
  - assets/icons/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  