name: flutter_auth_app
description: Flutter authentication app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  google_generative_ai: ^0.4.7
  just_audio: ^0.10.3
  audioplayers: ^6.4.0
  url_launcher: ^6.3.0
  decimal: ^2.3.3
  app_links: ^6.4.0
  flutter_vector_icons: ^2.0.0
  material_design_icons_flutter: ^7.0.7296
  collection: ^1.18.0
  # Thêm thư viện intl nếu bạn muốn sử dụng các tính năng quốc tế hóa, bao gồm định dạng ngày tháng
  intl: ^0.19.0 # Sử dụng phiên bản mới nhất hoặc phiên bản tương thích

assets:
  - assets/audio/
  - .env
  - assets/icons/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true